# This workflow will install Python dependencies, run tests, run linting, and build docs
name: Building Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # For on demand runs
  schedule:
    - cron: 0 0 * * * # Scheduled run every day at midnight
jobs:
  build:

    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: rstcheck
      run: |
        pip install -e .[style,docs,all]
        rstcheck -r docs 
    - name: Build docs
      run: sphinx-build docs docs/_build/html -W -b html